org.gradle.jvmargs=-Xmx3G -Dfile.encoding=COMPAT
org.gradle.parallel=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neoforge_version=26.3.0.39-beta
neoforge_version_range=[26.3.0.39-beta,26.4)
upstream_revision=330acd2d743bb6b2e27b53a4adb4a3c852b9e141

mod_id=caustica
mod_name=Caustica
mod_license=LGPL-3.0-or-later
mod_version=0.1.1-neoforge.2
maven_group=dev.comfyfluffy.caustica
archives_base_name=caustica-neoforge
