org.gradle.jvmargs=-Xmx3G -Dfile.encoding=GBK
org.gradle.parallel=true

minecraft_version=26.2
minecraft_version_range=[26.2,)
neoforge_version=26.2.0.57

mod_id=caustica
mod_name=Caustica
mod_license=LGPL-3.0-or-later
mod_version=0.0.1
maven_group=dev.comfyfluffy.caustica
archives_base_name=caustica
