modLoader="javafml"
loaderVersion="[11,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="ComfyFluffy and contributors"
description='''Hardware-ray-traced renderer with DLSS Ray Reconstruction for the Minecraft Vulkan backend. (NeoForge port)'''

[[mixins]]
config="caustica.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
